# ---- NOT WORKING ----  
- name: Run adolphsa/fleet_farm_logo:0.0.2 in Docker
  hosts: all
  become: yes
  become_user: root
  gather_facts: no
  tasks:
    - name: Run the FF logo Docker image
      docker_container:
        name: fleet_farm_logo
        image: adolphsa/fleet_farm_logo:0.0.2
        state: started
        expose:
          - 8080
        ports:
          - "8080:8080"
